services:

  # BROKER DE MENSAJES
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       
      - "15672:15672"    
    environment:
      RABBITMQ_DEFAULT_USER: grupo5
      RABBITMQ_DEFAULT_PASS: cbadenes
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bigdata_net


  task-producer:
    build: ./producer
    container_name: task-producer
    depends_on:
      rabbitmq:
        condition: service_healthy   
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: grupo5
      RABBITMQ_PASS: cbadenes
      TASK_RATE: 1                   # 1 tarea por segundo
    networks:
      - bigdata_net

  text-agent:
    build: ./text_agent
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: grupo5
      RABBITMQ_PASS: cbadenes
      LOGGER_URL: http://task-logger:8000
    volumes:
      - text_results:/data           # CSV persiste aunque el contenedor muera
    networks:
      - bigdata_net


  image-agent:
    build: ./image_agent
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: grupo5
      RABBITMQ_PASS: cbadenes
      LOGGER_URL: http://task-logger:8000
    volumes:
      - image_results:/data
    networks:
      - bigdata_net


  task-logger:
    build: ./task_logger
    container_name: task-logger
    ports:
      - "8000:8000"                
    networks:
      - bigdata_net

# VOLUMENES PERSISTENTES
volumes:
  text_results:    # almacena text_agent_results.csv
  image_results:   # almacena image_agent_results.csv

networks:
  bigdata_net:
    driver: bridge
